create table user_profile (
    id bigint generated by default as identity primary key,
    display_name varchar(80) not null,
    target_months integer not null check (target_months between 1 and 24),
    weekday_minutes integer not null check (weekday_minutes >= 0),
    weekend_minutes integer not null check (weekend_minutes >= 0),
    created_at timestamp with time zone not null default current_timestamp
);

create table learning_path (
    id bigint generated by default as identity primary key,
    language varchar(32) not null unique,
    position integer not null unique,
    status varchar(32) not null
);

create table lab (
    id varchar(40) primary key,
    path_id bigint not null references learning_path(id),
    number integer not null,
    slug varchar(120) not null,
    title varchar(180) not null,
    difficulty varchar(32) not null,
    threshold integer not null check (threshold between 0 and 100),
    type varchar(32) not null,
    unique (path_id, number),
    unique (path_id, slug)
);

create table attempt (
    id uuid primary key,
    lab_id varchar(40) not null references lab(id),
    started_at timestamp with time zone not null,
    completed_at timestamp with time zone,
    score numeric(5, 2),
    status varchar(40) not null
);

insert into learning_path (language, position, status)
values ('JAVA', 1, 'AVAILABLE'),
       ('PYTHON', 2, 'LOCKED'),
       ('TYPESCRIPT', 3, 'LOCKED');

insert into lab (id, path_id, number, slug, title, difficulty, threshold, type)
select 'JAVA-01', id, 1, 'syntaxe-compilation-jvm',
       'Syntaxe, compilation, JVM et premier programme', 'BASE', 70, 'LAB'
from learning_path
where language = 'JAVA';

